#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    filetree_direction = "left"
    bootstrap_after = 'myspacevim#after'
    colorscheme = "onedark"
    background = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false

    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "incsearch"

[[layers]]
    name = "ui"
    enable_scrollbar = true

[[layers]]
    name = 'colorscheme'
    enable = true

[[layers]]
  name = "lsp"
  enabled_clients =	['typescript-language-server', '--stdio']

[[layers]]
    name = 'ctrlp'

[[layers]]
  name = 'lang#html'
  enable = true

[[layers]]
  name = 'lang#java'
  enable = true

[[layers]]
  name = 'lang#javascript'
  enable = true

[[layers]]
  name = 'lang#markdown'
  enable = true

[[layers]]
  name = 'lang#typescript'
  enable = true

[[layers]]
  name = 'git'
  enable = true

[[layers]]
  name = 'github'
  enable = true

[[layers]]
  name = 'denite'
  enable = true

[[custom_plugins]]
    name = 'wakatime/vim-wakatime'
    enable = true

[[custom_plugins]]
    name = 'https://github.com/github/copilot.vim'
    enable = true
